### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by vunderkind**
Hey @DarrenN — I'm deeply sorry about this, but it looks like I never accepted your invite to this repository, which is why I had to fork to create this PR.

Could you reinvite me, please? I had to take some time to get the resources for the first Papers we Love event in Lagos, and I'm now poised to have one occur in September. 

Thank you, and I hope you're doing well?

### CODE REVIEW

**Comment by DarrenN** [comment]
Ok you've been added.

Check the link on the Code of Conduct.

**Comment by seun-beta** [comment]
Hello @vunderkind 

I hope you're good. I came across Papers We Love Lagos today and I saw that you're currently the coordinator. I would love to attend or help organise the event slated for September. Is there anyway we could connect?

**Comment by vunderkind** [comment]
Absolutely @seun-beta! 

Do you have a Telegram or WhatsApp account? I can create a group and add you in it if you leave your contact info. You can also email me via justin.irabor@gmail.com

**Comment by seun-beta** [comment]
Hello @vunderkind 

Yes, I am on Telegram and WhatsApp. I would shoot you a mail. Might not be the best for me to drop my private number on a public repo because of the number of bots that would scrape it  😂

**Pull request merged**
